#!/usr/bin/env bash
#
# gen-launcher.sh — generate the channel-specific Flatpak launcher script.
#
# The launcher is the ONLY per-channel artifact. ONE generator, TWO channels,
# a SINGLE manifest — no divergent manifests (avoids drift). The Flatpak manifest
# (`com.allow2.allow2linux.yml`) references the generated file as a `type: file`
# source, so every build entry point (build.sh, publish.sh, CI) calls this
# first to bake the right channel.
#
# ── Channels ─────────────────────────────────────────────────────────────────
#   staging     (the BETA channel, Flatpak Branch=beta):
#               OMITS ALLOW2_PRODUCTION and NODE_ENV=production, and bakes
#               ALLOW2_ENV=staging → the Allow2 SDK honours it and targets
#               staging-api.allow2.com. For INTERNAL TESTERS ONLY — never publish
#               this build as stable / to Flathub.
#
#   production  (the STABLE channel, Flatpak Branch=stable):
#               bakes ALLOW2_PRODUCTION=1 + NODE_ENV=production → the SDK's hard
#               guard ignores ALLOW2_ENV / ALLOW2_API_URL entirely and pins to
#               api.allow2.com. Staging is UNREACHABLE by any runtime input. This
#               is the production-locked build (the security guard's whole point).
#
# ── VID/TOKEN ────────────────────────────────────────────────────────────────
# The vid/token are TYPE IDENTIFIERS (which integration this is), NOT secrets, so
# they live in build-env *Variables* (not Secrets). Read from the environment with
# the known type ids as defaults, so a local `.env`-less build still works:
#   staging   : ALLOW2_STAGING_VID (default 21341) / ALLOW2_STAGING_TOKEN
#   production: ALLOW2_PROD_VID    (default 21599) / ALLOW2_PROD_TOKEN
#
# ── Usage ────────────────────────────────────────────────────────────────────
#   CHANNEL=staging     ./gen-launcher.sh [output-path]
#   CHANNEL=production  ./gen-launcher.sh [output-path]
# Default CHANNEL is production (the safe default for a naked build).
# Default output path is ./allow2linux.launcher.sh next to this script.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CHANNEL="${CHANNEL:-production}"
OUT="${1:-${SCRIPT_DIR}/allow2linux.launcher.sh}"

# Type-identifier defaults (NOT secrets). Overridable via build-env Variables.
STAGING_VID="${ALLOW2_STAGING_VID:-21341}"
STAGING_TOKEN="${ALLOW2_STAGING_TOKEN:-QhkiFFPVfMkUjLUR}"
PROD_VID="${ALLOW2_PROD_VID:-21599}"
PROD_TOKEN="${ALLOW2_PROD_TOKEN:-x9AUeUPpiweHTNCR}"

case "${CHANNEL}" in
  staging|beta)
    cat > "${OUT}" <<EOF
#!/bin/sh
# GENERATED by gen-launcher.sh — channel=staging (BETA). DO NOT EDIT.
#
# BETA channel: targets STAGING for internal testers. ALLOW2_PRODUCTION and
# NODE_ENV=production are DELIBERATELY OMITTED so the Allow2 SDK honours
# ALLOW2_ENV=staging and attaches to staging-api.allow2.com. Never ship this
# build as stable / to Flathub.
export ALLOW2_ENV=staging
export ALLOW2_VID=${STAGING_VID}
export ALLOW2_TOKEN=${STAGING_TOKEN}
exec /app/bin/node /app/lib/allow2linux/src/index.js "\$@"
EOF
    echo "==> launcher: channel=staging (BETA) → staging-api.allow2.com  vid=${STAGING_VID}  [prod flag OMITTED]"
    ;;
  production|stable)
    cat > "${OUT}" <<EOF
#!/bin/sh
# GENERATED by gen-launcher.sh — channel=production (STABLE). DO NOT EDIT.
#
# PRODUCTION SAFETY: bake the production flag so the Allow2 SDK ignores
# ALLOW2_ENV / ALLOW2_API_URL and can NEVER attach to staging. This is the
# production-locked build shipped publicly / to Flathub.
export ALLOW2_PRODUCTION=1
export NODE_ENV=production
export ALLOW2_VID=${PROD_VID}
export ALLOW2_TOKEN=${PROD_TOKEN}
exec /app/bin/node /app/lib/allow2linux/src/index.js "\$@"
EOF
    echo "==> launcher: channel=production (STABLE) → api.allow2.com  vid=${PROD_VID}  [prod flag BAKED]"
    ;;
  *)
    echo "ERROR: unknown CHANNEL='${CHANNEL}' (expected: staging|production)" >&2
    exit 1
    ;;
esac

chmod 755 "${OUT}"
echo "    wrote ${OUT}"
